package com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao.Employee;
import com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao.Customer;
import com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao.Invoice;
import com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao.InvoiceLine;

import com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao.EmployeeDao;
import com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao.CustomerDao;
import com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao.InvoiceDao;
import com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao.InvoiceLineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig employeeDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig invoiceDaoConfig;
    private final DaoConfig invoiceLineDaoConfig;

    private final EmployeeDao employeeDao;
    private final CustomerDao customerDao;
    private final InvoiceDao invoiceDao;
    private final InvoiceLineDao invoiceLineDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        employeeDaoConfig = daoConfigMap.get(EmployeeDao.class).clone();
        employeeDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        invoiceDaoConfig = daoConfigMap.get(InvoiceDao.class).clone();
        invoiceDaoConfig.initIdentityScope(type);

        invoiceLineDaoConfig = daoConfigMap.get(InvoiceLineDao.class).clone();
        invoiceLineDaoConfig.initIdentityScope(type);

        employeeDao = new EmployeeDao(employeeDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        invoiceDao = new InvoiceDao(invoiceDaoConfig, this);
        invoiceLineDao = new InvoiceLineDao(invoiceLineDaoConfig, this);

        registerDao(Employee.class, employeeDao);
        registerDao(Customer.class, customerDao);
        registerDao(Invoice.class, invoiceDao);
        registerDao(InvoiceLine.class, invoiceLineDao);
    }
    
    public void clear() {
        employeeDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        invoiceDaoConfig.getIdentityScope().clear();
        invoiceLineDaoConfig.getIdentityScope().clear();
    }

    public EmployeeDao getEmployeeDao() {
        return employeeDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public InvoiceDao getInvoiceDao() {
        return invoiceDao;
    }

    public InvoiceLineDao getInvoiceLineDao() {
        return invoiceLineDao;
    }

}
