package com.pinecone.technology.mcommerce.learning.android.chapter07.example.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EMPLOYEE.
 */
public class Employee {

    private Long id;
    /** Not-null value. */
    private String LastName;
    /** Not-null value. */
    private String FirstName;
    /** Not-null value. */
    private String Title;
    private Long ReportsTo;
    private java.util.Date BirthDate;
    private java.util.Date HireDate;
    private String Address;
    private String City;
    private String State;
    private String Country;
    private String PostalCode;
    private String Phone;
    private String Fax;
    private String Email;

    public Employee() {
    }

    public Employee(Long id) {
        this.id = id;
    }

    public Employee(Long id, String LastName, String FirstName, String Title, Long ReportsTo, java.util.Date BirthDate, java.util.Date HireDate, String Address, String City, String State, String Country, String PostalCode, String Phone, String Fax, String Email) {
        this.id = id;
        this.LastName = LastName;
        this.FirstName = FirstName;
        this.Title = Title;
        this.ReportsTo = ReportsTo;
        this.BirthDate = BirthDate;
        this.HireDate = HireDate;
        this.Address = Address;
        this.City = City;
        this.State = State;
        this.Country = Country;
        this.PostalCode = PostalCode;
        this.Phone = Phone;
        this.Fax = Fax;
        this.Email = Email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLastName() {
        return LastName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    /** Not-null value. */
    public String getFirstName() {
        return FirstName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    /** Not-null value. */
    public String getTitle() {
        return Title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String Title) {
        this.Title = Title;
    }

    public Long getReportsTo() {
        return ReportsTo;
    }

    public void setReportsTo(Long ReportsTo) {
        this.ReportsTo = ReportsTo;
    }

    public java.util.Date getBirthDate() {
        return BirthDate;
    }

    public void setBirthDate(java.util.Date BirthDate) {
        this.BirthDate = BirthDate;
    }

    public java.util.Date getHireDate() {
        return HireDate;
    }

    public void setHireDate(java.util.Date HireDate) {
        this.HireDate = HireDate;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getCity() {
        return City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    public String getState() {
        return State;
    }

    public void setState(String State) {
        this.State = State;
    }

    public String getCountry() {
        return Country;
    }

    public void setCountry(String Country) {
        this.Country = Country;
    }

    public String getPostalCode() {
        return PostalCode;
    }

    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    public String getPhone() {
        return Phone;
    }

    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    public String getFax() {
        return Fax;
    }

    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

}
